//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        [Display(Name="Текст сообщения")]
        public string UserName { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
